name: Integration
on:
  pull_request:
    branches: [ master ]
jobs:
  integrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1.1.0
      - name: Install
        run: yarn install
