name: Main
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-node@v1.1.0
    - name: CI
      run: |
        yarn install
    - name: CD
      if: job.status == 'success'
      uses: AkhileshNS/heroku-deploy@v3.0.0
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
